import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import ExcelJS from 'exceljs';

/**
 * Universal Export Service for ACETEL IAMS
 * Supports PDF, Excel (XLSX), and CSV
 */

const getBase64Image = (url: string): Promise<string> => {
    return new Promise((resolve, reject) => {
        const img = new Image();
        img.setAttribute('crossOrigin', 'anonymous');
        img.onload = () => {
            const canvas = document.createElement('canvas');
            canvas.width = img.width;
            canvas.height = img.height;
            const ctx = canvas.getContext('2d');
            ctx?.drawImage(img, 0, 0);
            const dataURL = canvas.toDataURL('image/png');
            resolve(dataURL);
        };
        img.onerror = (error) => reject(error);
        img.src = url;
    });
};

interface ExportConfig {
    fileName: string;
    title: string;
    headers: string[][];
    data: any[][];
    adminName?: string;
    logoUrl?: string;
}

export const exportToPDF = async (config: ExportConfig) => {
    const { fileName, title, headers, data, adminName = 'System Administrator' } = config;
    const doc = new jsPDF({ orientation: 'landscape' });
    const timestamp = new Date().toLocaleString();

    // --- Institutional Letterhead Implementation ---
    const logoY = 10;
    const logoSize = 25;
    const pageWidth = doc.internal.pageSize.width;
    
    // Load Logos as Base64 to ensure they are rendered
    try {
        const nounLogo = await getBase64Image('/images/noun-logo.png');
        doc.addImage(nounLogo, 'PNG', 14, logoY, logoSize, logoSize);
    } catch (e) {
        console.warn("NOUN Logo failed to load", e);
    }

    try {
        const acetelLogo = await getBase64Image('/images/acetel-logo.png');
        doc.addImage(acetelLogo, 'PNG', pageWidth - logoSize - 14, logoY, logoSize, logoSize);
    } catch (e) {
        console.warn("ACETEL Logo failed to load", e);
    }

    // Centered Branding Text
    doc.setTextColor(30, 58, 138); // ACETEL Blue
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text('NATIONAL OPEN UNIVERSITY OF NIGERIA (NOUN)', doc.internal.pageSize.width / 2, 18, { align: 'center' });
    
    doc.setTextColor(0, 135, 81); // Institutional Green
    doc.setFontSize(11);
    doc.text('AFRICA CENTER OF EXCELLENCE ON TECHNOLOGY ENHANCED LEARNING (ACETEL)', doc.internal.pageSize.width / 2, 25, { align: 'center' });

    doc.setTextColor(71, 85, 105);
    doc.setFontSize(12);
    doc.text(title.toUpperCase(), doc.internal.pageSize.width / 2, 33, { align: 'center' });

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(148, 163, 184);
    doc.text(`Institutional Audit Archive | Generated: ${timestamp}`, doc.internal.pageSize.width / 2, 39, { align: 'center' });

    // Add Table
    autoTable(doc, {
        startY: 48,
        head: headers,
        body: data,
        theme: 'grid',
        headStyles: { fillColor: [30, 58, 138], textColor: 255, fontStyle: 'bold' },
        styles: { fontSize: 8, cellPadding: 3 },
        alternateRowStyles: { fillColor: [248, 250, 252] },
    });

    // Add Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184);
        const footerY = doc.internal.pageSize.height - 10;
        doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.width - 30, footerY);
        doc.text(`Generated by: ${adminName} | Timestamp: ${timestamp} | ACETEL IAMS Production v1.0`, 14, footerY);
    }

    doc.save(`${fileName}_${new Date().getTime()}.pdf`);
};

export const exportGlobalInstitutionalReport = async (sections: { title: string, headers: string[][], data: any[][] }[], adminName: string) => {
    const doc = new jsPDF({ orientation: 'portrait' });
    const timestamp = new Date().toLocaleString();

    // --- Institutional Letterhead Implementation ---
    const logoY = 10;
    const logoSize = 25;
    const pageWidth = doc.internal.pageSize.width;
    
    // Load Logos as Base64
    try {
        const nounLogo = await getBase64Image('/images/noun-logo.png');
        doc.addImage(nounLogo, 'PNG', 14, logoY, logoSize, logoSize);
    } catch (e) { }

    try {
        const acetelLogo = await getBase64Image('/images/acetel-logo.png');
        doc.addImage(acetelLogo, 'PNG', pageWidth - logoSize - 14, logoY, logoSize, logoSize);
    } catch (e) { }

    // Centered Branding Text
    doc.setTextColor(30, 58, 138);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text('NATIONAL OPEN UNIVERSITY OF NIGERIA (NOUN)', pageWidth / 2, 18, { align: 'center' });
    
    doc.setTextColor(0, 135, 81);
    doc.setFontSize(12);
    doc.text('AFRICA CENTER OF EXCELLENCE ON TECHNOLOGY ENHANCED LEARNING (ACETEL)', pageWidth / 2, 26, { align: 'center' });

    doc.setTextColor(255, 255, 255);
    doc.setFillColor(30, 58, 138);
    doc.rect(0, 45, pageWidth, 40, 'F');
    doc.setFontSize(24);
    doc.text('ACETEL IAMS', pageWidth / 2, 62, { align: 'center' });
    doc.setFontSize(14);
    doc.text('MASTER INSTITUTIONAL PERFORMANCE REPORT', pageWidth / 2, 75, { align: 'center' });

    doc.setTextColor(30, 58, 138);
    doc.setFontSize(12);
    doc.text(`Reporting Period: ${new Date().getFullYear()} Academic Session`, pageWidth / 2, 105, { align: 'center' });
    doc.text(`Authorized by: ${adminName}`, pageWidth / 2, 115, { align: 'center' });
    doc.text(`Timestamp: ${timestamp}`, pageWidth / 2, 125, { align: 'center' });

    // 2. Sections
    let currentY = 150;
    doc.setFontSize(18);
    doc.text('TABLE OF CONTENTS', 14, currentY);
    currentY += 15;
    sections.forEach((s, i) => {
        doc.setFontSize(12);
        doc.text(`${i+1}. ${s.title}`, 14, currentY);
        currentY += 10;
    });

    // 3. Render Module Summaries
    sections.forEach((s) => {
        doc.addPage();
        doc.setFontSize(16);
        doc.setTextColor(0, 135, 81);
        doc.text(s.title.toUpperCase(), 14, 20);
        
        autoTable(doc, {
            startY: 30,
            head: s.headers,
            body: s.data, // Removed .slice(0, 50) for full institutional reports
            theme: 'striped',
            headStyles: { fillColor: [30, 58, 138] },
            styles: { fontSize: 7 }
        });
    });

    doc.save(`ACETEL_MASTER_REPORT_${new Date().getTime()}.pdf`);
};

export const exportToExcel = async ({ fileName, headers, data }: ExportConfig) => {
    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet('Institutional_Export');

    // Add headers and rows
    worksheet.addRows([...headers, ...data]);

    // Apply Institutional Styling
    const headerRow = worksheet.getRow(1);
    headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    headerRow.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FF1E3A8A' } // ACETEL Blue
    };
    
    // Column widths & auto-filter
    worksheet.columns.forEach(column => {
        column.width = 25;
    });
    worksheet.autoFilter = {
        from: { row: 1, column: 1 },
        to: { row: 1, column: headers[0].length }
    };

    // Buffer and Blob export
    const buffer = await workbook.xlsx.writeBuffer();
    const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${fileName}_${new Date().getTime()}.xlsx`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
};

export const exportToCSV = ({ fileName, headers, data }: ExportConfig) => {
    const csvContent = [
        headers[0].join(','),
        ...data.map(row => row.map(cell => `"${(cell || '').toString().replace(/"/g, '""')}"`).join(','))
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.setAttribute('download', `${fileName}_${new Date().getTime()}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
};
